### ISSUE TITLE
ResourceWarning: unclosed scandir iterator 

### ISSUE THREAD

**Issue by zopyx** [PyFilesystem/pyfilesystem2#311] opened 2019-07-21 09:13 UTC
Getting this warning under Python 3.7 for scandir():

/home/ajung/.buildout/eggs/fs-2.4.8-py3.7.egg/fs/osfs.py:521: ResourceWarning: unclosed scandir iterator <posix.ScandirIterator object at 0x7f61d00596b0>
  yield Info(info)

**Comment by willmcgugan** [comment] 2019-07-24 13:33
Do you have some code to reproduce this?

This will happen if you have an iterator to scandir that isn't full exhausted when it goes out of scope. It's not immediately obvious why it wouldn't close the native scandir iterator at the same time.

**Comment by althonos** [comment] 2021-03-27 03:27
Coming a bit late but I think the issue was caused by the following: since Python 3.6, `os.scandir` returns a handle that might not free all resources in case it is dropped before exhausted. This can happen in particular when `OSFS.scandir` is called with a ``page`` argument.

**Closed** 2021-03-27 03:33 UTC

**Comment by Apfelvater** [comment] 2025-11-18 10:21
for file in os.scandir(MyDir):
         if file.is_dir():
             if IsDesiredFile(file):
                 return file

Gives me the warning again:
XXX:25: ResourceWarning: unclosed scandir iterator <nt.ScandirIterator object at 0x000001CCE2E64D80>
  return file

(im working on the windows local appdata folder)
(Using Python 3.12 on Windows 11 GAC 24H2)

**Workaround**: Manually closing the iterator before breaking the loop:
```
MyDirIterator = os.scandir(MyDir)
for file in MyDirIterator:
     if file.is_dir():
         if IsDesiredFile(file):
             MyDirIterator.close()
             return file
```
