### ISSUE TITLE
Evaluated options for opener discovery

### ISSUE THREAD

**Issue by justvanrossum** [PyFilesystem/pyfilesystem2#228] opened 2018-11-08 13:40 UTC
I'm not sure this is indeed an `fs` issue, but perhaps it's at least good to have it documented here, too.

We're running into a problem with embedding `fs` into an application for MacOS with py2app, where the opener registry can't find anything, because the `entry_points.txt` file is not copied into the application, so `pkg_resources.iter_entry_points("fs.opener")` yields nothing.

See the related issue for py2app:
https://bitbucket.org/ronaldoussoren/py2app/issues/256/fs-module-not-fully-working-from-app

It seems the use of package metadata like `entry_points.txt` is problematic, and I wonder if there isn't a more friendly way to populate a registry such as `fs.opener`.

Cc @typemytype

**Comment by justvanrossum** [comment] 2018-11-08 13:41
Cc @anthrotype

**Comment by anthrotype** [comment] 2018-11-08 14:08
pyfilesystem2 uses setuptools' entry_points features to allow third-parties create extensions for additional filesystems and to load these dynamically when one does e.g. `open_fs('dropbox://~/projects')`.
I believe for simplicity, also the built-in filesystem implementations (like zip) are implemented using the same plugin technique, hence they are loaded with pkg_resources.iter_entry_point based on the entry_points.txt metadata.
I think the issue is with py2app which is dropping that metadata.

**Comment by willmcgugan** [comment] 2018-11-08 14:23
@justvanrossum I don't think we could give up the automatic opener registration at this point. But I'm certainly open to a workaround. Possibly a manual call to install the standard openers, but I'm open to suggestions...

**Comment by justvanrossum** [comment] 2018-11-08 14:29
> Possibly a manual call to install the standard openers

That would be useful, I think. For now, an example of how to do that would already be a big help.

**Comment by willmcgugan** [comment] 2018-11-08 16:03
I'm afraid I can't think of a quick patch.

We did used to have a manual system to register the openers that didn't use entry points, perhaps you can get that from the git history. You could at least package your app with a fork.

I'm hoping entry points can be fixed in py2app, but let's keep this issue open for now. Not sure when I'll get a chance to look at it, but I can help if you want to tackle this yourself.

**Comment by justvanrossum** [comment] 2018-11-08 16:04
As a workaround, we tried to add the `fs-2.1.1.dist-info` folder to the app bundle in the appropriate place, and now get the following exception:

`fs.opener.errors.EntryPointError: could not load entry point; The 'appdirs~=1.4.3' distribution was not found and is required by the application`

Even though the correct version `appdirs` is actually included. So it seems you have to go all the way with including meta info, or else.

To be honest, this is a major pain in the butt.

**Comment by anthrotype** [comment] 2018-11-08 16:07
@justvanrossum you'll have to include the `*.dist-info` for fs and all it's dependencies (`appdirs` and `pytz` for python3.6 which I think it's your target environment).

**Comment by justvanrossum** [comment] 2018-11-08 16:09
I just want to scream, is all.

**Comment by justvanrossum** [comment] 2018-11-08 16:14
> you'll have to include the *.dist-info for fs and all it's dependencies (appdirs and pytz for python3.6 which I think it's your target environment).

Also `six` and `setuptools`, and then it works. And there was much rejoicing.

**Comment by justvanrossum** [comment] 2018-11-08 17:03
Sorry for my grumpy tone today, I'm better now, thanks :)

`fs` is awesome, thanks for sharing it with the world!

**Comment by willmcgugan** [comment] 2018-11-09 19:21
Going to close this one then. Looks like it's a packaging problem, which is still a pain for Python.

I would like to add a little more flexibility to the opener system, so an application could explicitly define what openers are supported.

**Comment by justvanrossum** [comment] 2018-11-09 19:42
I still it's rather weak to depend on that meta info being there. But what is worse is that when it isn't, the error doesn't provide any useful clues about what actually goes wrong.

In my opinion you built-in openers should just work, even when the meta info is not available.

**Comment by althonos** [comment] 2018-11-09 21:13
Well, the problem is that Pyfilesystem2 buils with `setuptools` so I guess we rely on the standard packaging to just work. 

It may be possible however to revert back to manual registry handling and then trying to load the entry points. @willmcgugan, I might try patching this and open a PR, so you may keep this issue open if you want !

**Comment by justvanrossum** [comment] 2018-11-10 07:14
I think there's a huge difference between requiring `setuptools` for building/installing, and requiring it at runtime. The latter just makes things less portable/harder to deploy than necessary.

So yay from me for lifting that runtime requirement if possible!

**Comment by willmcgugan** [comment] 2018-11-10 11:42
@althonos OK. Renamed the issue to reflect that.

Perhaps the built in filesystems should be registered without entry points, using entry points only for external filesystems, and an option to manually register openers.

**Closed** 2018-12-23 16:44 UTC
Labels: accepted
