### ISSUE TITLE
FTPFS: getinfo() not working

### ISSUE THREAD

**Issue by nuschk** [PyFilesystem/pyfilesystem2#10] opened 2016-12-19 15:25 UTC
I'll get this exception if I try to use `getinfo()`:

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
[...]/env/lib/python3.5/site-packages/fs/ftpfs.py in getinfo(self, path, namespaces)
    439                 for raw_info in self._parse_mlsx(lines):
    440                     break
--> 441             return Info(raw_info)
    442         else:
    443             with ftp_errors(self, path=path):

UnboundLocalError: local variable 'raw_info' referenced before assignment
```
`response` is:

```
'250-Start of list for /images/89831.jpg\n250-modify=20161219151224;perm=adfrw;size=48312;type=file;unique=FC00U5606EA;UNIX.group=33;UNIX.mode=0644;UNIX.owner=33; /images/89831.jpg\n250 End of list'
``` 

at this point.

I could help with the PR, but you would have to point me in the right direction, as I'm a bit lost there.

**Comment by willmcgugan** [comment] 2016-12-19 15:57
I think the problem is where the "facts" lines are parsed (line 434). The code assumes that the facts lines should begin with a space, which is my reading of the rfc.

https://tools.ietf.org/html/rfc3659#page-37

But it doesn't look like that's what the server is returning.

So either I've misunderstood the spec, or the server isn't doing the right thing. Regardless, SFTP shouldn't throw an exception there.

Open to suggestions re the right way to fix that...

**Comment by nuschk** [comment] 2016-12-19 16:35
Thanks for your fast response. Well, you're right, the spec is pretty clear about the space character (`Notice that the fact line is indented by a single space.`). I'm no expert in FTP (and don't want to be one either...), but I don't see an easy fix here (...again, d'uh 🙄 ).

Would it be ok to disable the MLST feature through an added kwarg in the FTPFS' constructor?

**Comment by nuschk** [comment] 2016-12-19 16:37
Forgot to mention the obvious one: just drop the first and the last line of the response. But then again, that might not be a good idea...

**Comment by willmcgugan** [comment] 2016-12-19 16:51
I'd be tempted to try and parse it. The fallback would be in parsing the directory listings, which is even more awful. 

If you need a quick-fix, you could create a subclass with a property `supports_mlst` which returns False.

**Comment by nuschk** [comment] 2016-12-19 18:42
Yes, I already made that hack, thank you.

Here's a reply from another FTP server I have to consider, FWIW:
```
250-
Size=3139567;Modify=20161129195818;Type=file; MyPic.jpg

250 Requested file action okay, completed.
```
Yeah, an empty line. Seems like there's quite some variation in the various implementations.

**Comment by willmcgugan** [comment] 2016-12-19 19:31
The irony is that MLST was supposed to be a strict machine readable format. I'm going to close this issue, but I'll add a issue to make the mslx parser more lenient... Thanks for the bug report.

**Comment by willmcgugan** [comment] 2017-03-11 21:17
Just to let you know, I've pushed a change to the ftp directory parsing. Which may help. Would you mind giving it a try and letting me know how it goes?

**Comment by nuschk** [comment] 2017-03-12 09:24
Hey, thanks for this fix! Works for all my FTP targets (3 different servers) now.

**Comment by willmcgugan** [comment] 2017-03-26 19:54
Awesome. Version 2.0.2 includes the fix.

https://github.com/PyFilesystem/pyfilesystem2/releases/tag/v2.0.2

**Closed by willmcgugan** 2017-03-26 19:54 UTC
